source "https://rubygems.org"
gem "rake"
gem "thin"
gem "electron_opal", path: '..'

source 'https://gems.ruby-hyperloop.org'
gem "opal-jquery", git: "https://github.com/opal/opal-jquery.git", branch: "master"
gem "opal-rails", git: "https://github.com/opal/opal-rails.git", branch: "master"
gem 'hyper-component', '1.0.0.lap21', :source => 'https://gems.ruby-hyperloop.org/'
